"""empty message

Revision ID: 57811bdfc3d6
Revises: 9237c6743242
Create Date: 2025-06-03 19:01:38.981685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57811bdfc3d6'
down_revision = '9237c6743242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='user_post_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_post_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_post_pkey')
    )
    # ### end Alembic commands ###
